In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import string
import nltk
from nltk.corpus import stopwords
import statistics
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,SimpleRNN,GRU,Bidirectional
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

WARNING:tensorflow:From c:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [6]:
import os
print(os.getcwd())

c:\Users\Dell\Desktop\AML 10 EX

In [10]:
import os

path = r'C:\Users\Dell\Downloads\IMDB Dataset.csv'
print("Exists:", os.path.exists(path))

Exists: False

In [11]:
df = pd.read_csv(r'C:\Users\Dell\Downloads\IMDB Dataset.txt')

In [3]:
import pandas as pd

In [6]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\Dell\Downloads\IMDB Dataset.txt',
    delimiter=',',        # important
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

print(df.head())

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

In [16]:
def remove_html_tags(text):
  clean_text = re.sub(r'<.*?>', '', text)
  return clean_text

df['review'] = df['review'].apply(remove_html_tags)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
import string
punc = string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [18]:
def remove_punc(text):
  clean_text = "".join([char for char in text if char not in punc])
  return clean_text

df['review'] = df['review'].apply(remove_punc)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production The filming tech...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically theres a family where a little boy J...  negative
4  Petter Matteis Love in the Time of Money is a ...  positive

In [19]:
df['review'] =  df['review'].str.lower()

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\IMDB Dataset.txt")

In [3]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
def stp_words(text):
    clean_text = [
        word for word in str(text).split()
        if word not in stopwords.words('english')
    ]
    return " ".join(clean_text)

In [8]:
seq = token.texts_to_sequences(df['review'])

In [8]:
import pandas as pd
import nltk
from nltk.corpus import stopwords

# 1. Load dataset
df = pd.read_csv(
    r'C:\Users\Dell\Downloads\IMDB Dataset.txt',
    delimiter=',',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

print("Data Loaded ✅")

# 2. Setup stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 3. Function
def stp_words(text):
    return " ".join([word for word in text.split() if word not in stop_words])

# 4. Apply
df['review'] = df['review'].apply(stp_words)

print(df.head())

Data Loaded ✅

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                              review sentiment
0  One reviewers mentioned watching 1 Oz episode ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought wonderful way spend time hot summer ...  positive
3  Basically there's family little boy (Jake) thi...  negative
4  Petter Mattei's "Love Time Money" visually stu...  positive

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

WARNING:tensorflow:From c:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [5]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer

# 1. Load dataset
df = pd.read_csv(
    r'C:\Users\Dell\Downloads\IMDB Dataset.txt',
    delimiter=',',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

print("Dataset Loaded ✅")

# 2. Stopwords setup
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 3. Clean function
def stp_words(text):
    return " ".join([word for word in text.split() if word not in stop_words])

df['review'] = df['review'].apply(stp_words)

# 4. Tokenization
token = Tokenizer()
token.fit_on_texts(df['review'])

print("Tokenization Done ✅")
print(list(token.word_index.items())[:10])

Dataset Loaded ✅

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Tokenization Done ✅
[('br', 1), ('i', 2), ('the', 3), ('movie', 4), ('film', 5), ('one', 6), ('it', 7), ('like', 8), ('this', 9), ('good', 10)]

In [6]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer

# example (make sure df already exists!)
token = Tokenizer()

token.fit_on_texts(df['review'])

In [7]:
token = Tokenizer()
token.fit_on_texts(df['review'])

In [8]:
len(token.word_index)

124096

In [9]:
seq = token.texts_to_sequences(df['review'])

In [14]:
average = statistics.mean

In [15]:
average([len(x) for x in seq])

140.06574

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padding = pad_sequences(seq,maxlen=220,padding='pre')

In [11]:
padding.shape

(50000, 220)

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sentiment'] = le.fit_transform(df['sentiment'])

In [13]:
x= padding
y = df['sentiment']

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.175, random_state=42)

In [16]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((41250, 220), (8750, 220), (41250,), (8750,))

In [17]:
y.value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

In [18]:
vocab_size = len(token.word_index) + 1
print(f"Vocabulary size in x_train: {vocab_size}")

Vocabulary size in x_train: 124253

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
m1 = Sequential()
m1.add(Embedding(67142,100,input_length=220))
m1.add(SimpleRNN(150,return_sequences=True))
m1.add(SimpleRNN(50,return_sequences=True))
m1.add(SimpleRNN(25))
m1.add(Dense(1,activation='sigmoid'))
m1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 220, 100)          6714200

 simple_rnn_3 (SimpleRNN)    (None, 220, 150)          37650

 simple_rnn_4 (SimpleRNN)    (None, 220, 50)           10050

 simple_rnn_5 (SimpleRNN)    (None, 25)                1900

 dense_1 (Dense)             (None, 1)                 26

=================================================================
Total params: 6763826 (25.80 MB)
Trainable params: 6763826 (25.80 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
vocab_size = len(token.word_index) + 1
print(vocab_size)
m1 = Sequential()

m1.add(Embedding(input_dim=vocab_size, output_dim=100, input_length=220))
m1.add(SimpleRNN(150, return_sequences=True))
m1.add(Dense(1, activation='sigmoid'))
m1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

m1.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=500,
    validation_data=(x_test, y_test)
)

124253
Epoch 1/5
83/83 [==============================] - 129s 1s/step - loss: 0.6505 - accuracy: 0.6069 - val_loss: 0.6033 - val_accuracy: 0.6677
Epoch 2/5
83/83 [==============================] - 90s 1s/step - loss: 0.4907 - accuracy: 0.7384 - val_loss: 0.4987 - val_accuracy: 0.7216
Epoch 3/5
83/83 [==============================] - 124s 2s/step - loss: 0.4092 - accuracy: 0.7797 - val_loss: 0.5286 - val_accuracy: 0.7087
Epoch 4/5
83/83 [==============================] - 93s 1s/step - loss: 0.3776 - accuracy: 0.7965 - val_loss: 0.5255 - val_accuracy: 0.7294
Epoch 5/5
83/83 [==============================] - 93s 1s/step - loss: 0.3373 - accuracy: 0.8133 - val_loss: 0.6064 - val_accuracy: 0.7226

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dropout, Bidirectional
m1 = Sequential()
m2 = Sequential()
m2.add(Embedding(144771,output_dim=250,input_length=220))
m2.add(Bidirectional(LSTM(150,return_sequences=True)))
m2.add(Bidirectional(GRU(100,return_sequences=True)))
m2.add(Dropout(0.2))
m2.add(Bidirectional(LSTM(50,return_sequences=True)))
m2.add(Bidirectional(GRU(30,return_sequences=True)))
m2.add(Dropout(0.2))
m2.add(LSTM(10))
m2.add(Dense(1,activation='sigmoid'))

m2.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_4 (Embedding)     (None, 220, 250)          36192750

 bidirectional (Bidirection  (None, 220, 300)          481200
 al)

 bidirectional_1 (Bidirecti  (None, 220, 200)          241200
 onal)

 dropout (Dropout)           (None, 220, 200)          0

 bidirectional_2 (Bidirecti  (None, 220, 100)          100400
 onal)

 bidirectional_3 (Bidirecti  (None, 220, 60)           23760
 onal)

 dropout_1 (Dropout)         (None, 220, 60)           0

 lstm_2 (LSTM)               (None, 10)                2840

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 37042161 (141.30 MB)
Trainable params: 37042161 (141.30 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
m2.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
m2.fit(x,y,epochs=7,batch_size=500)

Epoch 1/7
  7/100 [=>............................] - ETA: 57:11 - loss: 0.6890 - accuracy: 0.5231

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dropout, Bidirectional, Dense
m3 = Sequential()
m3.add(Embedding(144771,output_dim=250,input_length=220))
m3.add(Bidirectional(LSTM(170,return_sequences=True)))
m3.add(Bidirectional(GRU(130,return_sequences=True)))
m3.add(Dropout(0.2))
m3.add(Bidirectional(LSTM(70,return_sequences=True)))
m3.add(Bidirectional(GRU(40,return_sequences=True)))
m3.add(Dropout(0.2))
m3.add(Bidirectional(GRU(20,return_sequences=True)))
m3.add(LSTM(20))
m3.add(Dense(1,activation='sigmoid'))
m3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 220, 250)          36192750

 bidirectional_5 (Bidirecti  (None, 220, 340)          572560
 onal)

 bidirectional_6 (Bidirecti  (None, 220, 260)          368160
 onal)

 dropout_2 (Dropout)         (None, 220, 260)          0

 bidirectional_7 (Bidirecti  (None, 220, 140)          185360
 onal)

 bidirectional_8 (Bidirecti  (None, 220, 80)           43680
 onal)

 dropout_3 (Dropout)         (None, 220, 80)           0

 bidirectional_9 (Bidirecti  (None, 220, 40)           12240
 onal)

 lstm_5 (LSTM)               (None, 20)                4880

 dense (Dense)               (None, 1)                 21

=================================================================
Total params: 37379651 (142.59 MB)
Trainable params: 37379651 (142.59 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [10]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\IMDB Dataset.txt")

In [11]:
x = df['review'].astype(str)
y = df['sentiment']

In [3]:
text = ['''Laapata Ladies is a sort of film that is very rare these days. A satire that is an eye-opener for the audience and needs everyone's attention. With unknown cast, limited budget and great script, it's a movie for all age-groups, every gender and is bound to go a long way.

This Kiran Rao's tragicomedy of two brides in rural India who accidentally get swapped during a train journey while returning from their wedding. Their misadventures after this strange event will make you laugh and the same time think about the social taboos a women has to go through in our society.

Ravi Kishan playing the cop investigating this case is a delight to watch. Very subtly and hilariously he gives movie the much needed comic side that perfectly balances the emotional cause for which the movie was made. Probably one of his best performance till date.
''']